### ISSUE TITLE
Typo in Plugin Name in Calibre Plugin List

### ISSUE THREAD

**Issue by andytinkham** [bertholdm/isfdb3-calibre#2]
I was having trouble finding the plugin in Calibre's list of new plugins to install, and I realized there is a typo in the name that was making it hard to find.

The name shows up as IFSDB3 (instead of ISFDB3 - the S & F are swapped).

**Comment by bertholdm** [comment]
Hello andytinkham,

thanks for reporting this. Since I don't have write permission for the plugin list, I reported this to Kovid.
